### ISSUE TITLE
[Bug grave] Banco unidades, Dps en millones

### ISSUE THREAD

**Issue by JesusNarvaezTames** [CCGLP/Clicker-Universitario#1]
Si bajas las unidades disponibles de 1 millón una vez has logrado un dps superior a 1 millón, dejan de incrementarse las unidades correctamente.

**Comment by CCGLP** [comment]
Bug solucionado en el siguiente commit. Ya funciona como debe, y si por ejemplo tienes un dps de 1M, aumenta rapidamente las unidades hasta volver a la liga millonaria
