### ISSUE TITLE
[Bug Grave] Dps millonario en unidades

### ISSUE THREAD

**Issue by JesusNarvaezTames** [CCGLP/Clicker-Universitario#2]
Si alcanzas 999,999 unidades en dps y tienes mas de 1 millón disponibles, al no llegar a 1 millón de dps, las unidades aumentan en 10 millones al segundo, en vez de 1 millón al segundo

**Comment by CCGLP** [comment]
Bug solucionado en el siguiente commit. Ya se comporta como debería subiendo "1millón" por segundo
